//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanNote.TESTS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CleanNote.TESTS.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;div style=&quot;direction:ltr;border-width:100%&quot;&gt;
        ///
        ///&lt;div style=&quot;direction:ltr;margin-top:0in;margin-left:0in;width:7.602in&quot;&gt;
        ///
        ///&lt;div style=&quot;direction:ltr;margin-top:0in;margin-left:0in;width:7.602in&quot;&gt;
        ///
        ///&lt;p style=&quot;margin:0in;font-family:Calibri;font-size:11.0pt&quot; lang=&quot;en-US&quot;&gt;This is
        ///an example of a OneNote-prepared blog post that is typically hard to convert to
        ///clean HTML.&lt;/p&gt;
        ///
        ///&lt;p style=&quot;margin:0in;font-family:Calibri;font-size:11.0pt&quot; lang=&quot;en-US&quot;&gt;&amp;nbsp;&lt;/p&gt;
        ///
        ///&lt;p style=&quot;margin:0in;font-family:Calibri;f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Borek01 {
            get {
                return ResourceManager.GetString("Borek01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///&lt;p style=&apos;margin:0in;font-family:&quot;Calibri Light&quot;;font-size:20.0pt&apos;&gt;Titulek
        ///stránky&lt;/p&gt;
        ///
        ///&lt;p style=&apos;margin:0in;font-family:Calibri;font-size:10.0pt;color:gray&apos;&gt;sobota,
        ///srpna 22, 2015&lt;/p&gt;
        ///
        ///&lt;p style=&apos;margin:0in;font-family:Calibri;font-size:10.0pt;color:gray&apos;&gt;5:03 PM&lt;/p&gt;
        ///
        ///&lt;p style=&apos;margin:0in;font-family:Calibri;font-size:16.0pt;color:#1E4E79&apos;&gt;Heading_1&lt;/p&gt;
        ///
        ///&lt;p style=&apos;margin:0in;font-family:Calibri;font-size:14.0pt;color:#2E75B5&apos;&gt;Heading_2&lt;/p&gt;
        ///
        ///&lt;p style=&apos;margin:0in;font-family:Calibri;font-size: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Headings_And_Formating {
            get {
                return ResourceManager.GetString("Headings_And_Formating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///&lt;p style=&apos;margin:0in;font-family:&quot;Calibri Light&quot;;font-size:20.0pt&apos;&gt;Titulek
        ///stránky&lt;/p&gt;
        ///
        ///&lt;p style=&apos;margin:0in;font-family:Calibri;font-size:10.0pt;color:gray&apos;&gt;čtvrtek,
        ///srpna 20, 2015&lt;/p&gt;
        ///
        ///&lt;p style=&apos;margin:0in;font-family:Calibri;font-size:10.0pt;color:gray&apos;&gt;1:18 AM&lt;/p&gt;
        ///
        ///&lt;p style=&apos;margin:0in;font-family:Calibri;font-size:16.0pt;color:#1E4E79&apos;&gt;Heading_1&lt;/p&gt;
        ///
        ///&lt;p style=&apos;margin:0in;font-family:Calibri;font-size:14.0pt;color:#2E75B5&apos;&gt;Heading_2&lt;/p&gt;
        ///
        ///&lt;p style=&apos;margin:0in;font-family:Calibri;font-size [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JustHeadings {
            get {
                return ResourceManager.GetString("JustHeadings", resourceCulture);
            }
        }
    }
}
